# Generated by Django 3.2.16 on 2022-12-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_proimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imager', models.ImageField(blank=True, default='', null=True, upload_to='car')),
                ('company_name', models.CharField(max_length=100)),
                ('car_name', models.CharField(choices=[('Maruti', 'Maruti'), ('Hyundai', 'Hyundai'), ('Tata', 'Tata'), ('Mahindra', 'Mahindra'), ('Kia', 'Kia'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Renault', 'Renault'), ('Honda', 'Honda'), ('MG', 'MG'), ('Nissan', 'Nisaan'), ('Datsun', 'Datsun'), ('Toyota', 'Toyota'), ('Honda', 'Honda')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2014'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4)),
                ('rent', models.IntegerField(max_length=200)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], max_length=10)),
                ('seating_capacity', models.CharField(choices=[('3', '3'), ('5', '5'), ('7', '7')], max_length=1)),
                ('milege', models.IntegerField(max_length=20)),
                ('engine', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
            ],
        ),
    ]
