# Generated by Django 3.2.16 on 2022-12-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProImage',
        ),
        migrations.AlterField(
            model_name='car',
            name='milege',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent',
            field=models.IntegerField(),
        ),
    ]
