# Generated by Django 3.2.16 on 2022-12-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20221219_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='displayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(default='', upload_to='dimg')),
                ('Image2', models.ImageField(default='', upload_to='dimg')),
                ('Image3', models.ImageField(default='', upload_to='dimg')),
                ('Image4', models.ImageField(default='', upload_to='dimg')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='', upload_to='img')),
                ('image2', models.ImageField(default='', upload_to='img')),
                ('image3', models.ImageField(default='', upload_to='img')),
                ('image4', models.ImageField(default='', upload_to='img')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('image6', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('image7', models.ImageField(blank=True, default='', null=True, upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
