# Generated by Django 3.2.16 on 2022-12-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_catering_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='booking_price',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tax_rate',
            field=models.IntegerField(max_length=200),
        ),
    ]
