# Generated by Django 3.2.16 on 2022-12-23 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20221223_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='venuecateringcombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_price', models.IntegerField(max_length=200)),
                ('max_invitees', models.IntegerField(max_length=200)),
                ('price_per_plate', models.IntegerField(max_length=200)),
                ('tax_rate', models.IntegerField(max_length=200)),
                ('discounted_price', models.IntegerField(max_length=200)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='venuecatering',
        ),
    ]
