# Generated by Django 3.2.16 on 2022-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20221226_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='discounted_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='catering',
            name='price_per_plate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='catering',
            name='tax_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='booking_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='max_invitees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tax_rate',
            field=models.IntegerField(),
        ),
    ]
