# Generated by Django 3.2.16 on 2022-12-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20221226_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecateringcombined',
            name='discounted_price',
            field=models.IntegerField(),
        ),
    ]
