# Generated by Django 3.2.16 on 2022-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_venuecateringcombined_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='dhol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_of_1_dhol', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('total_hour', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='musicall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_price', models.IntegerField()),
                ('total_hour', models.IntegerField()),
                ('price_of_1_dhol', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
            ],
        ),
    ]
