# Generated by Django 3.2.16 on 2022-12-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_dhol_dj_musicall'),
    ]

    operations = [
        migrations.CreateModel(
            name='portpolio_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default=False, max_length=200)),
                ('package_intro', models.TextField(default=False)),
                ('package_price', models.IntegerField(default=False)),
                ('location', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('indoor_outdoor_shoot', models.TextField(default=True, max_length=500)),
                ('styling_makeup', models.TextField()),
                ('costume', models.TextField()),
                ('intro_video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
