# Generated by Django 3.2.16 on 2023-01-01 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_portpolio_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='prewedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField()),
                ('discounted_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dhol',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='displayimage',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dj',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musicall',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portpolio_package',
            name='comp_card',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portpolio_package',
            name='portpolio_book',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portpolio_package',
            name='poster_size_print',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portpolio_package',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portpolio_package',
            name='visiting_card_of_model',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='portpolio_package',
            name='costume',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='portpolio_package',
            name='duration',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='portpolio_package',
            name='intro_video',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='portpolio_package',
            name='location',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='portpolio_package',
            name='styling_makeup',
            field=models.TextField(default=True),
        ),
        migrations.CreateModel(
            name='wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField()),
                ('discounted_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField()),
                ('discounted_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='combined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField()),
                ('discounted_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
