# Generated by Django 3.2.16 on 2023-01-02 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20230101_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='prewedding',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='weddingmakeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField()),
                ('discounted_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='preweddingmakeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField()),
                ('discounted_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='engmakeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField()),
                ('discounted_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='allmakeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField()),
                ('discounted_price', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
