# Generated by Django 3.2.16 on 2023-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20230102_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='catering_with_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_25person', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='catering_without_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_25person', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='food_per_plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_plate', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
            ],
        ),
    ]
